apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2020-07-13T03:53:33Z"
  generation: 3
  labels:
    app: hello
  name: hello
  namespace: schedule-pods
  resourceVersion: "2359741"
  selfLink: /apis/extensions/v1beta1/namespaces/schedule-pods/deployments/hello
  uid: 6bff13c7-c4bc-11ea-b6c0-0a9c0d887b9f
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello
    spec:
      containers:
      - image: quay.io/redhattraining/hello-world-nginx:v1.0
        imagePullPolicy: IfNotPresent
        name: hello-world-nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        env: prod
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2020-07-13T03:58:22Z"
    lastUpdateTime: "2020-07-13T03:58:22Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-07-13T04:24:15Z"
    lastUpdateTime: "2020-07-13T04:24:24Z"
    message: ReplicaSet "hello-5899495986" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
